name: CI/CD Pipeline

 

on:
  push:
    branches:
      - Development  # Changer "Developpement" en la branche que vous souhaitez déclencher

 

jobs:
  test:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

 

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11  # Assurez-vous que la version Java est correcte pour votre projet (11 est un exemple)

 

    - name: Check Java Version
      run: java -version

 

    - name: Run Tests with Maven
      run: |
        mvn test  # Assurez-vous que la commande Maven pour exécuter vos tests est correcte

 

  upload-coverage:
    needs: test
    runs-on: ubuntu-latest

 

    steps:
    - name: Upload Coverage Reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Assurez-vous que votre jeton Codecov est stocké dans les secrets GitHub

 

# N'oubliez pas d'ajuster les noms de tâches, les versions Java, les commandes Maven et toute autre configuration nécessaire en fonction de votre projet Spring Boot.
